inherit_from: .rubocop_todo.yml

# Minitest specs and Sequel migrations have long blocks so exclude them from the
# BlockLength check
Metrics/BlockLength:
  Exclude:
    - 'test/**/*'
    - 'db/migrations/**/*'

# We have some long attribute names that mean our line lengths are longer than
# usual. This is something we might want to fix in the future but we're unlikely
# to for now.
Metrics/LineLength:
  Enabled: false

# This cop gets incorrectly trigged for code inside Sequel's virtual row block
# http://sequel.jeremyevans.net/rdoc/files/doc/dataset_filtering_rdoc.html#label-Filtering+using+expressions
# e.g. records.where { pm2_5_concentration_ug_per_m3 > 0 }
Style/NumericPredicate:
  Enabled: false
